function artifacts = demo_publication_figure(projectRoot)
%DEMO_PUBLICATION_FIGURE Generate a reproducible contest-paper figure.

if nargin < 1
    projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
workspace = setup_modeling_path(projectRoot);
rng(20260801, 'twister');

demand = (60:5:120).';
replicates = 48;
baselineCenter = 54 + 0.57 * demand - 0.0018 * (demand - 90).^2;
optimizedCenter = baselineCenter .* (1.075 + 0.012 * exp(-((demand - 95) / 18).^2));
noiseScale = 2.2 + 0.014 * demand;
baselineSamples = baselineCenter + noiseScale .* randn(numel(demand), replicates);
optimizedSamples = optimizedCenter + 0.88 * noiseScale .* randn(numel(demand), replicates);

baselineMean = mean(baselineSamples, 2);
optimizedMean = mean(optimizedSamples, 2);
baselineCI95 = 1.96 * std(baselineSamples, 0, 2) / sqrt(replicates);
optimizedCI95 = 1.96 * std(optimizedSamples, 0, 2) / sqrt(replicates);
improvementPct = 100 * (optimizedMean - baselineMean) ./ baselineMean;

alpha = linspace(0.70, 1.30, numel(demand)).';
sensitivityLow = 100 - 14 * (alpha - 1).^2 - 2.2 * (alpha - 1);
sensitivityMedium = 100 - 19 * (alpha - 1).^2 + 0.7 * (alpha - 1);
sensitivityHigh = 100 - 25 * (alpha - 1).^2 + 3.0 * (alpha - 1);
stableMask = alpha >= 0.80 & alpha <= 1.20;
stableDeviationPct = max(abs([sensitivityLow(stableMask); sensitivityMedium(stableMask); ...
    sensitivityHigh(stableMask)] - 100));

resultTable = table(demand, baselineMean, baselineCI95, optimizedMean, optimizedCI95, ...
    improvementPct, alpha, sensitivityLow, sensitivityMedium, sensitivityHigh, ...
    'VariableNames', {'DemandIndex', 'BaselineMean', 'BaselineCI95', 'OptimizedMean', ...
    'OptimizedCI95', 'ImprovementPct', 'Alpha', 'SensitivityLow', ...
    'SensitivityMedium', 'SensitivityHigh'});
csvPath = fullfile(workspace.outputRoot, 'demo_result.csv');
matPath = fullfile(workspace.outputRoot, 'demo_result.mat');
writetable(resultTable, csvPath);
save(matPath, 'resultTable', 'baselineSamples', 'optimizedSamples', 'replicates', ...
    'stableDeviationPct');

fig = figure('Visible', 'off', 'Color', 'white', 'Units', 'centimeters', ...
    'Position', [2, 2, 18.0, 8.4]);
cleanup = onCleanup(@() close(fig));
layout = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

ax1 = nexttile(layout);
style = applyModelingStyle(ax1);
hold(ax1, 'on');
baselineBand = 0.82 + 0.18 * style.palette.gray;
optimizedBand = 0.84 + 0.16 * style.palette.blue;
patch(ax1, [demand; flipud(demand)], ...
    [baselineMean - baselineCI95; flipud(baselineMean + baselineCI95)], ...
    baselineBand, 'EdgeColor', 'none', 'HandleVisibility', 'off');
patch(ax1, [demand; flipud(demand)], ...
    [optimizedMean - optimizedCI95; flipud(optimizedMean + optimizedCI95)], ...
    optimizedBand, 'EdgeColor', 'none', 'HandleVisibility', 'off');
pBaseline = plot(ax1, demand, baselineMean, '--s', 'Color', style.palette.gray, ...
    'LineWidth', style.lineWidth, 'MarkerSize', style.markerSize, ...
    'MarkerFaceColor', 'white', 'MarkerIndices', 1:2:numel(demand));
pOptimized = plot(ax1, demand, optimizedMean, '-o', 'Color', style.palette.blue, ...
    'LineWidth', style.lineWidth + 0.15, 'MarkerSize', style.markerSize, ...
    'MarkerFaceColor', 'white', 'MarkerIndices', 1:2:numel(demand));
hold(ax1, 'off');
xlabel(ax1, '需求指数（无量纲）', 'Interpreter', 'none');
ylabel(ax1, '期望收益（万元）', 'Interpreter', 'none');
title(ax1, '(a) 优化方案与基线（均值及 95% CI）', 'Interpreter', 'none');
legend(ax1, [pOptimized, pBaseline], {'优化方案', '基线方案'}, ...
    'Location', 'northwest', 'Box', 'off', 'Color', 'none', ...
    'TextColor', style.textColor, 'FontName', style.fontName, 'FontSize', 8.2);
text(ax1, 0.98, 0.06, sprintf('平均提升 %.1f%%', mean(improvementPct)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom', ...
    'FontName', style.fontName, 'FontSize', 8.2, 'Color', style.palette.blue);

ax2 = nexttile(layout);
applyModelingStyle(ax2, 'FontName', style.fontName, 'FontSize', style.fontSize);
hold(ax2, 'on');
xregion(ax2, 0.80, 1.20, 'FaceColor', style.palette.fill, ...
    'EdgeColor', 'none', 'HandleVisibility', 'off');
pLow = plot(ax2, alpha, sensitivityLow, '--s', 'Color', style.palette.orange, ...
    'LineWidth', style.lineWidth, 'MarkerSize', style.markerSize, 'MarkerFaceColor', 'white');
pMedium = plot(ax2, alpha, sensitivityMedium, '-o', 'Color', style.palette.blue, ...
    'LineWidth', style.lineWidth + 0.15, 'MarkerSize', style.markerSize, 'MarkerFaceColor', 'white');
pHigh = plot(ax2, alpha, sensitivityHigh, '-.^', 'Color', style.palette.teal, ...
    'LineWidth', style.lineWidth, 'MarkerSize', style.markerSize, 'MarkerFaceColor', 'white');
xline(ax2, 1.0, ':', 'Color', style.palette.ink, ...
    'LineWidth', 1.0, 'HandleVisibility', 'off');
scatter(ax2, 1.0, 100, 28, 'o', 'MarkerEdgeColor', style.palette.ink, ...
    'MarkerFaceColor', 'white', 'LineWidth', 1.0, 'HandleVisibility', 'off');
hold(ax2, 'off');
xlabel(ax2, '关键参数相对值 \alpha', 'Interpreter', 'tex');
ylabel(ax2, '归一化目标值（基准 = 100）', 'Interpreter', 'none');
title(ax2, '(b) 参数灵敏度与稳定区间', 'Interpreter', 'none');
ylim(ax2, [96.8, 100.5]);
legend(ax2, [pLow, pMedium, pHigh], {'低需求', '中需求', '高需求'}, ...
    'Location', 'southoutside', 'NumColumns', 3, 'Box', 'off', 'Color', 'none', ...
    'TextColor', style.textColor, 'FontName', style.fontName, 'FontSize', 8.0);
text(ax2, 0.62, 100.42, sprintf('稳定区间内最大偏差 %.1f%%', stableDeviationPct), ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'top', ...
    'FontName', style.fontName, 'FontSize', 8.2, 'Color', style.palette.improved);
text(ax2, 1.01, 97.02, '\alpha = 1', 'Interpreter', 'tex', ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'bottom', ...
    'FontName', style.fontName, 'FontSize', 8.0, 'Color', style.textColor);

basePath = fullfile(workspace.outputRoot, 'demo');
artifacts = exportModelingFigure(fig, basePath, 'Resolution', 400);
artifacts.csv = csvPath;
artifacts.mat = matPath;

contract = struct( ...
    'id', 'fig-demo-main-sensitivity', ...
    'claim', '优化方案在全部需求水平优于基线，且关键参数在正负 20% 范围内变化时目标值保持稳定。', ...
    'evidence', 'output/_demos/matlab/matlab_figures/demo_result.csv:BaselineMean,OptimizedMean,ImprovementPct,Alpha,SensitivityLow,SensitivityMedium,SensitivityHigh', ...
    'role', 'main-result-and-sensitivity', ...
    'chart_type', 'two-panel-line-with-confidence-band', ...
    'palette_id', 'journal-spectrum-v2', ...
    'color_encoding', {{'primary=optimized; baseline=gray; highlight=threshold; line styles and markers provide second encoding'}}, ...
    'encoding', '颜色表示方案或情景；实线、虚线、点划线及点型提供灰度下的第二编码。', ...
    'axes', {{'需求指数（无量纲）/期望收益（万元）', '参数相对值/归一化目标值'}}, ...
    'baseline', '左图为基线方案，右图为参数相对值 1.0 时的归一化目标值 100。', ...
    'caption', '不同需求水平下优化方案与基线的期望收益及 95% 置信区间，以及三种需求情景下关键参数的灵敏度。', ...
    'export', {{'pdf', 'svg', 'png'}}, ...
    'random_seed', 20260801, ...
    'replicates', replicates);
contractPath = fullfile(workspace.outputRoot, 'demo_figure_contract.json');
writeJson(contractPath, contract);
artifacts.contract = contractPath;
artifactsPath = fullfile(workspace.outputRoot, 'demo_artifacts.json');
writeJson(artifactsPath, artifacts);
fprintf('MATLAB publication demo written to %s\n', workspace.outputRoot);
end

function writeJson(path, value)
fileId = fopen(path, 'w', 'n', 'UTF-8');
assert(fileId >= 0, 'Unable to open JSON output: %s', path);
cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, jsonencode(value, PrettyPrint=true), 'char');
end
