function mm_demo_panel_label(ax, label, style)
%MM_DEMO_PANEL_LABEL Add a consistent publication panel label.
text(ax, 0.015, 0.985, label, 'Units', 'normalized', ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'top', ...
    'FontName', style.fontName, 'FontSize', 9, 'FontWeight', 'bold', ...
    'Color', style.textColor, 'Clipping', 'off', 'Interpreter', 'none');
end
