function outputs = mf_export_triplet(fig, outputDir, stem, S)
% Export vector PDF/SVG and a 400 dpi PNG with a shared stem.
if ~isfolder(outputDir)
    mkdir(outputDir);
end
outputs = strings(3, 1);
outputs(1) = fullfile(outputDir, stem + ".pdf");
outputs(2) = fullfile(outputDir, stem + ".svg");
outputs(3) = fullfile(outputDir, stem + ".png");
canvas = fig.Position;
exportgraphics(fig, outputs(1), 'ContentType', 'vector', ...
    'BackgroundColor', S.colors.background, 'Units', 'centimeters', ...
    'Width', canvas(3), 'Height', canvas(4), 'Padding', 'figure', ...
    'PreserveAspectRatio', 'off');
exportgraphics(fig, outputs(2), 'ContentType', 'vector', ...
    'BackgroundColor', S.colors.background, 'Units', 'centimeters', ...
    'Width', canvas(3), 'Height', canvas(4), 'Padding', 'figure', ...
    'PreserveAspectRatio', 'off');
exportgraphics(fig, outputs(3), 'Resolution', S.pngDpi, ...
    'BackgroundColor', S.colors.background, 'Units', 'centimeters', ...
    'Width', canvas(3), 'Height', canvas(4), 'Padding', 'figure', ...
    'PreserveAspectRatio', 'off');
end
