function report = prepare_figure_data(projectRoot, stagingRoot)
% Derive figure-only data from frozen C-problem experiment artifacts.
scriptDir = fileparts(mfilename('fullpath'));
if nargin < 1 || strlength(string(projectRoot)) == 0
    projectRoot = fileparts(fileparts(scriptDir));
end
if nargin < 2 || strlength(string(stagingRoot)) == 0
    stagingRoot = scriptDir;
end
projectRoot = string(projectRoot);
stagingRoot = string(stagingRoot);
addpath(fullfile(stagingRoot, 'helpers'));

derivedDir = fullfile(stagingRoot, 'derived');
reportDir = fullfile(stagingRoot, 'reports');
if ~isfolder(derivedDir), mkdir(derivedDir); end
if ~isfolder(reportDir), mkdir(reportDir); end

rel = [ ...
    "results/C/claims.json"; ...
    "problems/C/questions/Q1/question.yaml"; ...
    "problems/C/questions/Q2/question.yaml"; ...
    "problems/C/questions/Q3/question.yaml"; ...
    "problems/C/questions/Q4/question.yaml"; ...
    "experiments/C/Q1/q1-direct-20260808/models/forecast_q1/workload_panel.csv"; ...
    "experiments/C/Q1/q1-direct-20260808/models/forecast_q1/blind_test_predictions.csv"; ...
    "experiments/C/Q1/q1-direct-20260808/models/forecast_q1/metrics_by_series.csv"; ...
    "experiments/C/Q1/q1-direct-20260808/models/scheduling_q1/optimized_schedule.csv"; ...
    "experiments/C/Q1/q1-direct-20260808/models/scheduling_q1/resource_audit.csv"; ...
    "experiments/C/Q2/q2-direct-20260808/models/full_horizon/q2_full_hourly_profiles.csv"; ...
    "experiments/C/Q2/q2-direct-20260808/models/full_horizon/q2_full_baseline_schedule.csv"; ...
    "experiments/C/Q2/q2-direct-20260808/models/full_horizon/q2_full_candidate_schedule.csv"; ...
    "experiments/C/Q2/q2-full-compat-20260808/q2_compat_summary.json"; ...
    "experiments/C/Q3/q3-direct-20260808/models/rolling_milp/q3_dispatch.csv"; ...
    "experiments/C/Q3/q3-direct-20260808/models/rolling_milp/q3_comparison_summary.csv"; ...
    "experiments/C/Q3/q3-full-audit-fix-20260809/summary.json"; ...
    "experiments/C/Q4/q4-optimization-20260809/q4_joint_metrics.csv"; ...
    "experiments/C/Q4/q4-optimization-20260809/q4_formal_summary.json"; ...
    "experiments/C/Q4/q4-optimization-20260809/q4_joint_observed_joint_candidate_dispatch.csv"; ...
    "experiments/C/Q4/q4-optimization-20260809/q4_joint_observed_sequential_baseline_dispatch.csv"; ...
    "experiments/C/Q1/q1-direct-20260808/models/forecast_q1/metrics_summary.json"; ...
    "experiments/C/Q1/q1-direct-20260808/models/scheduling_q1/constraint_audit.json"; ...
    "experiments/C/Q1/q1-direct-20260808/models/scheduling_q1/scheduling_metrics.json"; ...
    "experiments/C/Q4/q4-optimization-20260809/q4_joint_constraint_audit.json"; ...
    "experiments/C/Q2/q2-direct-20260808/models/full_horizon/q2_full_constraint_audit.json" ...
    ];

entries = repmat(struct('path', "", 'sha256', "", 'bytes', 0), numel(rel), 1);
for k = 1:numel(rel)
    absPath = fullfile(projectRoot, rel(k));
    if ~isfile(absPath)
        error('matlabFigures:MissingInput', 'Required frozen input is missing: %s', absPath);
    end
    info = dir(absPath);
    entries(k).path = rel(k);
    entries(k).sha256 = mf_sha256(absPath);
    entries(k).bytes = info.bytes;
end

P = @(r) fullfile(projectRoot, r);
D = struct();

% Q1: weekly structure across the 18 region-task series.
W = readtable(P(rel(6)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(W, {'ArrivalHour','SourceRegion','TaskType','GPU_Workload_GPUh'}, rel(6));
regions = sort(unique(string(W.SourceRegion)));
taskTypes = unique(string(W.TaskType), 'stable');
weekHour = (0:167).';
weekly = nan(numel(regions) * numel(taskTypes), 168);
labels = strings(size(weekly, 1), 1);
taskDisplay = containers.Map( ...
    {'RealTimeInference','BatchInference','AITraining'}, ...
    {'Real-time','Batch','Training'});
row = 0;
for r = 1:numel(regions)
    for t = 1:numel(taskTypes)
        row = row + 1;
        regionLabel = replace(regions(r), "Region", "Region ");
        taskLabel = taskTypes(t);
        if isKey(taskDisplay, char(taskTypes(t)))
            taskLabel = string(taskDisplay(char(taskTypes(t))));
        end
        labels(row) = regionLabel + " | " + taskLabel;
        mask = string(W.SourceRegion) == regions(r) & string(W.TaskType) == taskTypes(t);
        hmod = mod(double(W.ArrivalHour(mask)), 168);
        values = double(W.GPU_Workload_GPUh(mask));
        for h = 0:167
            weekly(row, h + 1) = median(values(hmod == h), 'omitnan');
        end
        finiteValues = sort(values(isfinite(values)));
        scale = finiteValues(max(1, ceil(0.95 * numel(finiteValues))));
        if scale > 0
            weekly(row, :) = weekly(row, :) / scale;
        end
    end
end
D.q1Weekly = struct('weekHour', weekHour, 'seriesLabels', labels, ...
    'normalizedGpuHours', weekly, 'dayCenters', (12:24:156).', ...
    'dayLabels', "Day " + string((1:7).'));

% Q1: aggregate all 18 blind-test series to the system level.
B = readtable(P(rel(7)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(B, {'period','hour','region','task_type','actual_gpu_h', ...
    'baseline_gpu_h','main_gpu_h','main_lower_95_gpu_h','main_upper_95_gpu_h'}, rel(7));
B = B(string(B.period) == "blind_test", :);
hour = sort(unique(double(B.hour)));
hourIndex = double(B.hour) - min(hour) + 1;
nHours = numel(hour);
D.q1Forecast = struct('hour', hour, ...
    'relativeHour', hour - min(hour), ...
    'actual', accumarray(hourIndex, double(B.actual_gpu_h), [nHours, 1], @sum, 0), ...
    'baseline', accumarray(hourIndex, double(B.baseline_gpu_h), [nHours, 1], @sum, 0), ...
    'main', accumarray(hourIndex, double(B.main_gpu_h), [nHours, 1], @sum, 0), ...
    'lower95', accumarray(hourIndex, double(B.main_lower_95_gpu_h), [nHours, 1], @sum, 0), ...
    'upper95', accumarray(hourIndex, double(B.main_upper_95_gpu_h), [nHours, 1], @sum, 0), ...
    'region', "System", 'taskType', "All", ...
    'selectionRule', "sum of all 18 bottom-level series by blind-test hour");

% Q1: paired blind-test MAE for all 18 series.
M = readtable(P(rel(8)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(M, {'period','method','region','task_type','mae_gpu_h'}, rel(8));
M = M(string(M.period) == "blind_test", :);
pairKeys = unique(string(M.region) + " | " + string(M.task_type), 'stable');
baselineMae = nan(numel(pairKeys), 1);
mainMae = nan(numel(pairKeys), 1);
for k = 1:numel(pairKeys)
    keyMask = string(M.region) + " | " + string(M.task_type) == pairKeys(k);
    baseMask = keyMask & contains(string(M.method), "seasonal_baseline");
    mainMask = keyMask & contains(string(M.method), "shared_hgbr_reconciled");
    if nnz(baseMask) ~= 1 || nnz(mainMask) ~= 1
        error('matlabFigures:PairingFailure', 'Q1 metric pairing failed for %s.', pairKeys(k));
    end
    baselineMae(k) = double(M.mae_gpu_h(baseMask));
    mainMae(k) = double(M.mae_gpu_h(mainMask));
end
D.q1ErrorPairs = struct('seriesLabels', pairKeys, ...
    'baselineMae', baselineMae, 'mainMae', mainMae);

% Q1: final-day schedule and normalized resource headroom.
S1 = readtable(P(rel(9)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(S1, {'TaskID','TaskType','ExecutionRegion','StartMinute','EndMinute', ...
    'SchedulePhase','GPU_Demand'}, rel(9));
D.q1Schedule = S1;
R = readtable(P(rel(10)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(R, {'Hour','Region','GPU_margin','GPU_capacity','IT_margin_MW', ...
    'IT_capacity_MW','Facility_margin_MW','Facility_capacity_MW','Schedule'}, rel(10));
R = R(string(R.Schedule) == "optimized" & double(R.Hour) >= 2376 & double(R.Hour) < 2400, :);
resourceHours = sort(unique(double(R.Hour)));
gpuUtilization = nan(numel(regions), numel(resourceHours));
itHeadroom = nan(size(gpuUtilization));
facilityHeadroom = nan(size(gpuUtilization));
for r = 1:numel(regions)
    maskRegion = string(R.Region) == regions(r);
    for h = 1:numel(resourceHours)
        mask = maskRegion & double(R.Hour) == resourceHours(h);
        gpuUtilization(r, h) = 100 * (1 - ...
            double(R.GPU_margin(mask)) / double(R.GPU_capacity(mask)));
        itHeadroom(r, h) = 100 * ...
            double(R.IT_margin_MW(mask)) / double(R.IT_capacity_MW(mask));
        facilityHeadroom(r, h) = 100 * ...
            double(R.Facility_margin_MW(mask)) / double(R.Facility_capacity_MW(mask));
    end
end
D.q1Headroom = struct('hour', resourceHours, 'relativeHour', resourceHours - min(resourceHours), ...
    'regions', replace(regions, "Region", "Region "), ...
    'gpuUtilizationPct', gpuUtilization, 'itHeadroomPct', itHeadroom, ...
    'facilityHeadroomPct', facilityHeadroom);

% Q2: facility-load migration and cumulative cost/carbon effects.
P2 = readtable(P(rel(11)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(P2, {'Method','Hour','Region','Facility_Load_MW','ElectricityCost_CNY', ...
    'CarbonEmission_tCO2'}, rel(11));
methods = unique(string(P2.Method), 'stable');
baseMethod = methods(find(contains(methods, "FIFO"), 1));
candMethod = methods(find(~contains(methods, "FIFO"), 1));
q2Regions = sort(unique(string(P2.Region)));
hours2 = (0:max(double(P2.Hour))).';
migration = nan(numel(q2Regions), 168);
for r = 1:numel(q2Regions)
    rb = string(P2.Region) == q2Regions(r) & string(P2.Method) == baseMethod;
    rc = string(P2.Region) == q2Regions(r) & string(P2.Method) == candMethod;
    baseLoad = accumarray(double(P2.Hour(rb)) + 1, double(P2.Facility_Load_MW(rb)), ...
        [numel(hours2), 1], @mean, NaN);
    candLoad = accumarray(double(P2.Hour(rc)) + 1, double(P2.Facility_Load_MW(rc)), ...
        [numel(hours2), 1], @mean, NaN);
    delta = candLoad - baseLoad;
    migration(r, :) = accumarray(mod(hours2, 168) + 1, delta, [168, 1], @mean, NaN).';
end
D.q2Migration = struct('weekHour', (0:167).', 'regions', q2Regions, ...
    'deltaFacilityMW', migration, 'baselineMethod', baseMethod, 'candidateMethod', candMethod, ...
    'dayCenters', (12:24:156).', 'dayLabels', "Day " + string((1:7).'));

mb = string(P2.Method) == baseMethod;
mc = string(P2.Method) == candMethod;
baseCost = accumarray(double(P2.Hour(mb)) + 1, double(P2.ElectricityCost_CNY(mb)), ...
    [numel(hours2), 1], @sum, 0);
candCost = accumarray(double(P2.Hour(mc)) + 1, double(P2.ElectricityCost_CNY(mc)), ...
    [numel(hours2), 1], @sum, 0);
baseCarbon = accumarray(double(P2.Hour(mb)) + 1, double(P2.CarbonEmission_tCO2(mb)), ...
    [numel(hours2), 1], @sum, 0);
candCarbon = accumarray(double(P2.Hour(mc)) + 1, double(P2.CarbonEmission_tCO2(mc)), ...
    [numel(hours2), 1], @sum, 0);
cumBaseCost = cumsum(baseCost);
cumBaseCarbon = cumsum(baseCarbon);
costPct = 100 * (cumsum(candCost) - cumBaseCost) ./ cumBaseCost;
carbonPct = 100 * (cumsum(candCarbon) - cumBaseCarbon) ./ cumBaseCarbon;
costPct(~isfinite(costPct)) = NaN;
carbonPct(~isfinite(carbonPct)) = NaN;
D.q2Cumulative = struct('hour', hours2, 'costDifferencePct', costPct, ...
    'carbonDifferencePct', carbonPct, 'baselineMethod', baseMethod, 'candidateMethod', candMethod);

SB = readtable(P(rel(12)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
SC = readtable(P(rel(13)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(SB, {'TaskID','NetworkLatency_ms'}, rel(12));
mf_require_columns(SC, {'TaskID','NetworkLatency_ms'}, rel(13));
baseIds = string(SB.TaskID);
candIds = string(SC.TaskID);
if numel(baseIds) ~= 50000 || numel(candIds) ~= 50000 || ...
        numel(unique(baseIds)) ~= numel(baseIds) || ...
        numel(unique(candIds)) ~= numel(candIds) || ...
        ~isequal(sort(baseIds), sort(candIds))
    error('matlabFigures:Q2LatencyPairing', ...
        'Q2 latency inputs must contain the same 50000 unique TaskIDs.');
end
if any(~isfinite(double(SB.NetworkLatency_ms))) || any(~isfinite(double(SC.NetworkLatency_ms)))
    error('matlabFigures:Q2LatencyFinite', 'Q2 latency inputs contain non-finite values.');
end
q2Audit = jsondecode(fileread(P(rel(26))));
if ~isfield(q2Audit, 'baseline') || ~isfield(q2Audit, 'candidate') || ...
        ~isfield(q2Audit.baseline, 'SLA_violation_rate') || ...
        ~isfield(q2Audit.candidate, 'SLA_violation_rate')
    error('matlabFigures:Q2LatencyAudit', 'Q2 constraint audit lacks the SLA fields required by the figure.');
end
baselineSlaRate = double(q2Audit.baseline.SLA_violation_rate);
candidateSlaRate = double(q2Audit.candidate.SLA_violation_rate);
if baselineSlaRate ~= 0 || candidateSlaRate ~= 0
    error('matlabFigures:Q2LatencySLA', 'The frozen Q2 latency figure requires zero SLA violations for both schedules.');
end
if ~q2Audit.baseline.checks.latency_limit || ~q2Audit.candidate.checks.latency_limit
    error('matlabFigures:Q2LatencyLimit', ...
        'Both Q2 schedules must pass the independent MaxLatency hard check.');
end
D.q2Latency = struct('baselineMs', double(SB.NetworkLatency_ms), ...
    'candidateMs', double(SC.NetworkLatency_ms), ...
    'baselineMethod', baseMethod, 'candidateMethod', candMethod, ...
    'baselineSlaViolationRate', baselineSlaRate, ...
    'candidateSlaViolationRate', candidateSlaRate, ...
    'baselineSlaViolationCount', double(q2Audit.baseline.SLA_violation_count), ...
    'candidateSlaViolationCount', double(q2Audit.candidate.SLA_violation_count), ...
    'baselineLatencyLimitPassed', logical(q2Audit.baseline.checks.latency_limit), ...
    'candidateLatencyLimitPassed', logical(q2Audit.candidate.checks.latency_limit), ...
    'baselineTaskCount', numel(baseIds), 'candidateTaskCount', numel(candIds), ...
    'baselineAtFiveMsPct', 100 * mean(abs(double(SB.NetworkLatency_ms) - 5) < 1e-12));

% Q3: observed 72-hour aggregate operation and rolling solver coverage.
P3All = readtable(P(rel(15)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(P3All, {'Hour','Region','ChargePower_MW','DischargePower_MW','SOC_MWh', ...
    'NetGridImport_MW','Evaluation','Scenario','WindowStart_h'}, rel(15));
mask3 = string(P3All.Evaluation) == "fixed" & string(P3All.Scenario) == "observed" & ...
    double(P3All.WindowStart_h) == 0 & double(P3All.Hour) < 72;
P3 = P3All(mask3, :);
hours3 = (0:71).';
D.q3Dispatch = struct('hour', hours3, ...
    'chargeMW', accumarray(double(P3.Hour) + 1, double(P3.ChargePower_MW), [72, 1], @sum, 0), ...
    'dischargeMW', accumarray(double(P3.Hour) + 1, double(P3.DischargePower_MW), [72, 1], @sum, 0), ...
    'socMWh', accumarray(double(P3.Hour) + 1, double(P3.SOC_MWh), [72, 1], @sum, 0), ...
    'netGridImportMW', accumarray(double(P3.Hour) + 1, double(P3.NetGridImport_MW), [72, 1], @sum, 0));

C3 = readtable(P(rel(16)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(C3, {'evaluation','scenario','window_start_h','region','runtime_s_candidate'}, rel(16));
C3 = C3(string(C3.evaluation) == "rolling_block" & string(C3.scenario) == "observed", :);
q3Regions = sort(unique(string(C3.region)));
windowStarts = sort(unique(double(C3.window_start_h)));
runtime = nan(numel(q3Regions), numel(windowStarts));
for r = 1:numel(q3Regions)
    for h = 1:numel(windowStarts)
        mask = string(C3.region) == q3Regions(r) & double(C3.window_start_h) == windowStarts(h);
        if nnz(mask) ~= 1
            error('matlabFigures:Q3Coverage', 'Expected one Q3 rolling solve for %s at %g.', ...
                q3Regions(r), windowStarts(h));
        end
        runtime(r, h) = double(C3.runtime_s_candidate(mask));
    end
end
audit3 = jsondecode(fileread(P(rel(17))));
D.q3Runtime = struct('regions', replace(q3Regions, "Region", "Region "), ...
    'windowStartHour', windowStarts, 'blockIndex', (1:numel(windowStarts)).', ...
    'blockLengthHours', [diff(windowStarts); ...
        max(double(P3All.Hour)) + 1 - windowStarts(end)], ...
    'runtimeSeconds', runtime, ...
    'auditsPassed', double(audit3.audit_boundary.total_audits_passed), ...
    'auditsTotal', double(audit3.audit_boundary.total_audit_count));

% Q4: five-scenario trade-off and observed 72-hour profile differences.
M4 = readtable(P(rel(18)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(M4, {'scenario','role','cost_CNY','carbon_tCO2', ...
    'positive_peak_MW','renewable_utilization_ratio'}, rel(18));
scenarioKeys = unique(string(M4.scenario), 'stable');
scenarioDisplay = ["Observed"; "Peak-price"; "High-carbon"; ...
    "Low-renewable"; "Joint stress"];
if numel(scenarioKeys) ~= numel(scenarioDisplay)
    error('matlabFigures:Q4Scenarios', ...
        'Expected five Q4 scenarios, found %d.', numel(scenarioKeys));
end
delta = nan(numel(scenarioKeys), 4);
for k = 1:numel(scenarioKeys)
    baseMask = string(M4.scenario) == scenarioKeys(k) & ...
        string(M4.role) == "sequential_baseline";
    candMask = string(M4.scenario) == scenarioKeys(k) & ...
        string(M4.role) == "joint_candidate";
    if nnz(baseMask) ~= 1 || nnz(candMask) ~= 1
        error('matlabFigures:Q4Pairing', ...
            'Q4 scenario pairing failed for %s.', scenarioKeys(k));
    end
    delta(k, :) = [ ...
        double(M4.cost_CNY(candMask) - M4.cost_CNY(baseMask)) / 1e3, ...
        double(M4.carbon_tCO2(candMask) - M4.carbon_tCO2(baseMask)), ...
        100 * double(M4.renewable_utilization_ratio(candMask) - ...
            M4.renewable_utilization_ratio(baseMask)), ...
        double(M4.positive_peak_MW(candMask) - M4.positive_peak_MW(baseMask))];
end
improvement = [-delta(:, 1), -delta(:, 2), delta(:, 3), -delta(:, 4)];
normalizedImprovement = zeros(size(improvement));
for j = 1:size(improvement, 2)
    scale = max(abs(improvement(:, j)), [], 'omitnan');
    if scale > 0
        normalizedImprovement(:, j) = improvement(:, j) / scale;
    end
end
audit4 = jsondecode(fileread(P(rel(25))));
D.q4Tradeoff = struct('scenarioKeys', scenarioKeys, ...
    'scenarioLabels', scenarioDisplay, ...
    'metricLabels', ["Net cost"; "Purchase carbon"; "Renewable use"; "Positive peak"], ...
    'deltaValues', delta, 'normalizedImprovement', normalizedImprovement, ...
    'taskCompletionRate', double(audit4.task_schedule.task_completion_rate), ...
    'slaViolationRate', double(audit4.task_schedule.SLA_violation_rate), ...
    'meanLatencyMs', double(audit4.task_schedule.mean_latency_ms), ...
    'p95LatencyMs', double(audit4.task_schedule.p95_latency_ms));
QC = readtable(P(rel(20)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
QB = readtable(P(rel(21)), 'TextType', 'string', 'VariableNamingRule', 'preserve');
mf_require_columns(QC, {'Hour','AI_IT_Load_MW','NetGridImport_MW'}, rel(20));
mf_require_columns(QB, {'Hour','AI_IT_Load_MW','NetGridImport_MW'}, rel(21));
hours4 = (0:max(double(QC.Hour))).';
candidateAI = accumarray(double(QC.Hour) + 1, double(QC.AI_IT_Load_MW), [numel(hours4), 1], @sum, 0);
baselineAI = accumarray(double(QB.Hour) + 1, double(QB.AI_IT_Load_MW), [numel(hours4), 1], @sum, 0);
candidateGrid = accumarray(double(QC.Hour) + 1, double(QC.NetGridImport_MW), [numel(hours4), 1], @sum, 0);
baselineGrid = accumarray(double(QB.Hour) + 1, double(QB.NetGridImport_MW), [numel(hours4), 1], @sum, 0);
D.q4Profile = struct('hour', hours4, ...
    'deltaAiItMW', candidateAI - baselineAI, ...
    'deltaNetGridImportMW', candidateGrid - baselineGrid);

dataPath = fullfile(derivedDir, 'figure_data.mat');
save(dataPath, 'D', '-v7');
report = struct();
report.schema_version = 1;
report.project_id = "huashu-cup-2026";
report.problem_id = "C";
report.backend = "MATLAB";
report.matlab_release = string(version('-release'));
report.generated_at = string(datetime('now', 'TimeZone', 'local', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX'));
report.input_hashes = entries;
report.derived_data = struct('path', "derived/figure_data.mat", ...
    'sha256', mf_sha256(dataPath));
report.q1_forecast_aggregation = struct('level', D.q1Forecast.region, ...
    'series', D.q1Forecast.taskType, 'rule', D.q1Forecast.selectionRule);
mf_write_json(fullfile(reportDir, 'input_hashes.json'), report);
end

